//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_FFOOD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_info
    {
        public int billinfo_id { get; set; }
        public int id_bill { get; set; }
        public int id_food { get; set; }
        public int id_account { get; set; }
        public int count { get; set; }
        public decimal price { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Account Account { get; set; }
        public virtual Bill Bill { get; set; }
    }
}
