//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_FFOOD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LTWEB_FFoodEntities : DbContext
    {
        public LTWEB_FFoodEntities()
            : base("name=LTWEB_FFoodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill_info> Bill_info { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Food_Catagory> Food_Catagory { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
    }
}
